### ISSUE TITLE
xd.gov doesn't resolve

### ISSUE THREAD

**Issue by afeld** [XDgov/xd.gov#6]
@lukad03 Just discovered that the following URLs work:

- http://www.xd.gov/
- https://www.xd.gov/
- https://xdgov.github.io/xd.gov/

but the following don't:

- http://xd.gov/
- https://xd.gov/

Just in case y'all weren't aware!

**Comment by lukad03** [comment]
And it never will 🤣 Well, at least until we are able to either a) create a redirect record for the root domain or b) create a A record for the root domain. Hoping to revisit this down the line.

For now - www.xd.gov works.
